spring:
  application:
    name: gateway
  # cloud:
  #   gateway:
  #       routes:
  #       - id: studentService
  #         uri: http://localhost:9091
  #         predicates:
  #           - Path=/api/student/**
  #       - id: teacherService
  #         uri: http://localhost:9092
  #         predicates:
  #           - Path=/api/teacher/**
  #       - id: IdentityService
  #         uri: http://localhost:8081
  #         predicates:
  #         - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/mobileSystem
          jwk-set-uri: http://localhost:9080/realms/mobileSystem/protocol/openid-connect/certs

server:
  port: 8087
